class StartPageConsts:
    SUBSCRIBE_EMAIL_XPATH = './/input[@name="email"]'
    SUBSCRIBE_NAME_XPATH = './/input[@name="name"]'
    SUBSCRIBE_SURNAME_XPATH = './/input[@name="surname"]'
    SUBSCRIBE_SIGNUP_XPATH = './/button[@class="AppButton_button__NqGGr  Subscribe_formBtn__O5CW1"]'
    SUBSCRIBE_VERIFY_XPATH = './/p[@class="Text_text__65_FH alertStore_title__uh2ba"]'
    SUBSCRIBE_VERIFY_TEXT = 'Thanks for subscribing. Make sure you have our mobile app to find the best places to get outdoors.'
    CREATE_ACC_HOMEPAGE_XPATH = './/a[@class="AppButton_linkBtn__rmRkI HeaderNav_linkBtn__rZZ6c"][@href="/create-account"]'
    VERIFY_CREATE_ACC_XPATH = './/button[contains(text(),"Sign up with email")]'
    SIGN_UP_EMAIL_PLACEHOLDER = './/input[@placeholder="Email"]'
    SIGN_UP_PASSWORD_PLACEHOLDER = './/input[@placeholder="Password"]'
    CREATE_ACC_BUTTON_XPATH = './/button[contains(text(), "Create an Account")]'
    SUCCESSFUL_SIGN_UP_XPATH = './/p[contains(text(), "Congratulations!")]'
    VERIFY_SUCCESSFUL_TEXT = 'Congratulations!'
    ENTER_PHONE_NUM_XPATH = './/input[@placeholder="Enter phone number"]'
    SEND_LINK_XPATH = './/button[contains(text(), "Send Link")]'
    SIGN_UP_WITH_EMAIL_XPATH = './/button[contains(text(), "Sign up with email")]'
    SIGN_UP_CODE_XPATH = './/select[@name="code"]'
    CODE_SELECTION_XPATH = './/option[contains(text(), "{option}")]'
    OPTION_US_TEXT = 'US +1'
    OPTION_MX_TEXT = 'MX +52'
    SIGN_UP_EMAIL_USED_XPATH = './/p[contains(text(), "The email address is already in use by another account.")]'
    SIGN_UP_EMAIL_USED_TEXT = 'The email address is already in use by another account.'
